### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Wilczeek** [digiwombat/TalkerMakerDeluxe#4]
EASY:
1.Delete characters
I believe this is an oversight - you can't delete character even if it doesn't have any dialogue nodes.

2.Draw a line between linked nodes
As a graphical representation, it would be nice if a linked node had a line connecting with the second one (just like subnodes do). 

3.Subnodes with multiple parents
One big missing feature is no ability to add a one subnode for multiple parent nodes. It could work as a 'reverse tree' and therefor save user from having multiple copies of the same child dialogue lines.
![mockup](https://cloud.githubusercontent.com/assets/7970548/9655660/1355fbca-5233-11e5-844e-5357145a52af.png)
(Suggestions marked with a RED lines.)

HARD:
4. Custom export
Talker Maker is a great alternative to Chat Mapper, and it would be nice if it supported custom exporting - not only to Unity-based systems. Since all fields in the conversations have their generic names, user could easily specify his own exporting pattern. For example, it would be possible to turn off Menu Text or Sequence if they aren't being used. As a more time-consuming feature, maybe it would be possible to expand it to define very own exporting format, allowing user to drop json or xml in favor of their own needs.

**Comment by digiwombat** [comment]
1) Deleting characters is something I intend on adding. I think there's a few other things you can't delete either. This will go into the next major set of things I add.

2) Good idea, will add assuming I can make it look not cluttered. Otherwise, will do something like double clicking to move to the linked node. But yeah, should be SOME visual indication.

3) Functionally, this is how Link To works. Links are forced end nodes and since their passthrough can only either send you to the next node or back up the chain to the one above it in the logical order. 

Example using your image: Node 2, using Link To, can only passthrough to Nope 3. While it won't be indicated this way visually, it will work that way functionally. To explain a bit further: Node 2 will play to Node 3 if you check Link To: and input 3. If you then go to six, it will Link back to 2 which will play through to 3. However, if I were to add an option in between one and two which DID NOT link to 3, the graph would become a mess. Considering visual reordering requires just way more work than it's worth, I think your suggestion for number 2 (some visual link) will probably suffice here.

4) I actually really like the idea here, but it will require writing a parser. Wouldn't be too hard but would take a bit of time. Will definitely consider it.

**Comment by digiwombat** [comment]
Closing as pretty much all of these are in except the custom export which isn't really in-scope for the project unless a ton of people want to come on and do a ton of work. Haha.

That is to say, I don't need the feature and I'm more worried about straight dialogue writing and functionality related to that (Variables, Lua, etc).
